name: ci-pr-workflow
on: 
  pull_request:
    types:
      - opened
      - closed
      - synchronize
    branches: 
      - 'main'
  push:
    branches: 
      - 'feature/merge-branch'
jobs:
  execute-shell-python-job:
    runs-on: ubuntu-latest
    steps: 
      - name: checkout repository
        uses: actions/checkout@v4

      - name: print the currect dir details
        run: |
          pwd
      - name: execute the shell file
        run: |
          chmod +x *
          ./app.sh
        working-directory: app
      - name: execute the python file
        run: python3 app.py
        working-directory: app
  
  print-repository-details-job:
    runs-on: ubuntu-latest
    steps:
      - name: print-owner
        run: | 
          echo "Repository Name: $GITHUB_REPOSITORY"
          echo "Repo Owner: $GITHUB_REPOSITORY_OWNER"



      
