name: Falsk-CI-Worlflow
on:
  push: 

jobs:
  flask-ci-job:
    runs-on: ubuntu-latest
    
    steps:
      - name: checkout repository
        uses: actions/checkout@v7
      
      # - name: validate the repository
      #   run: |
      #     pwd
      #     ls -la
      #     find . -maxdepth 4 -type f -name "Dockerfile" -print
      
      - name: docker image build
        run: |
          cd projectfiles
          docker build -t flask-github:v1.0 .
      
      - name: list out images
        run: docker images
        
